version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: ${APP_BUILD_TARGET:-development}
    volumes:
      - type: bind
        source: ./php-src
        target: /data

  kotlin:
    build:
      context: .
      dockerfile: ./docker/kotlin/Dockerfile
      target: ${KOTLIN_BUILD_TARGET:-development}
    tty: true
    volumes:
      - type: bind
        source: ./kotlin-src
        target: /data
    environment:
      - IS_CI=false
