name: Kotlin Build CI

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "kotlin-src/**"
      - ".github/workflows/kotlin_build.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Build with gradle (ktlint)
        run: ./gradlew build
        working-directory: kotlin-src
        env:
          IS_CI: "true"
